# Generated by Django 6.0 on 2025-12-29 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms_co', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=200)),
                ('category_content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TermsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Terms and Conditions', max_length=200)),
                ('intro_content', models.TextField(help_text='This content appears below the main title')),
                ('last_updated', models.DateField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TermsAndConditions',
        ),
        migrations.AddField(
            model_name='termscategory',
            name='terms_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='terms_co.termspage'),
        ),
    ]
